version: 0.2
phases:
  install:
     commands:
       - sudo apt-get update
       - sudo apt-get install docker.io -y
       - sudo systemctl enable docker.service    
   
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 719658110167.dkr.ecr.ap-southeast-1.amazonaws.com
      - 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ak2-ecr .
      - docker tag ak2-ecr:latest 719658110167.dkr.ecr.ap-southeast-1.amazonaws.com/ak2-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 719658110167.dkr.ecr.ap-southeast-1.amazonaws.com/ak2-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name”:"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

